### ISSUE TITLE
alloy/no-unused-vars not working for alloy binding methods

### ISSUE THREAD

**Issue by jasonkneen** [tidev/eslint-plugin-alloy#57]
I'm getting eslint warnings for this rule when using transform; filter functions so events are fine like `onClick` etc -- they work as intended but if my XML has `dataTransform="transformLocation"` or `dataFilter="filterLocation"` then any declarations of these functions in the controller are flagged as being unused.

**Comment by ewanharris** [comment]
I imagine the findEventHandlers function needs to be updated to include looking for these properties

 https://github.com/appcelerator/eslint-plugin-alloy/blob/4f62a4f3c3bd723322f201a2f7d962dc916f6ea5/lib/utils.js#L53-L60

**Comment by ewanharris** [comment]
This is now released as 1.2.0
